-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2014.1
-- Copyright (C) 2014 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ap_ctl_handler is
port (
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_start_enable : IN STD_LOGIC;
    ap_start_out : OUT STD_LOGIC;
    ap_ready_in : IN STD_LOGIC;
    ap_done_in : IN STD_LOGIC;
    ap_idle_in : IN STD_LOGIC;
    ap_status_out_V : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of ap_ctl_handler is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "ap_ctl_handler,hls_ip_2014_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.728500,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=0}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_true : BOOLEAN := true;
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

    signal p_s_fu_78_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal current_status_V_fu_86_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal current_status_V_1_fu_94_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal current_status_V_fu_86_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_s_fu_78_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal current_status_V_1_fu_94_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_102_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_04_1_fu_120_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal current_status_V_2_fu_112_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_04_1_fu_120_p3 : STD_LOGIC_VECTOR (2 downto 0);


begin



    ap_done <= ap_start;
    ap_idle <= ap_const_logic_1;
    ap_ready <= ap_start;
    ap_start_out <= '0' when (p_04_1_fu_120_p3 = ap_const_lv3_0) else '1';
    current_status_V_1_fu_94_p0 <= (0=>ap_done_in, others=>'-');
    current_status_V_1_fu_94_p3 <= 
        current_status_V_fu_86_p3 when (current_status_V_1_fu_94_p0(0) = '1') else 
        p_s_fu_78_p3;
    current_status_V_2_fu_112_p3 <= (tmp_1_fu_102_p4 & ap_const_lv1_1);
    current_status_V_fu_86_p0 <= (0=>ap_ready_in, others=>'-');
    current_status_V_fu_86_p3 <= 
        ap_const_lv3_6 when (current_status_V_fu_86_p0(0) = '1') else 
        ap_const_lv3_2;
    p_04_1_fu_120_p0 <= (0=>ap_idle_in, others=>'-');
    p_04_1_fu_120_p3 <= 
        current_status_V_2_fu_112_p3 when (p_04_1_fu_120_p0(0) = '1') else 
        current_status_V_1_fu_94_p3;
    p_s_fu_78_p0 <= (0=>ap_ready_in, others=>'-');
    p_s_fu_78_p3 <= 
        ap_const_lv3_4 when (p_s_fu_78_p0(0) = '1') else 
        ap_const_lv3_0;
    tmp_1_fu_102_p4 <= current_status_V_1_fu_94_p3(2 downto 1);
end behav;
