# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2013.4
# Copyright (C) 2013 Xilinx Inc. All rights reserved.
# 
# ==============================================================

proc generate {drv_handle} {
    xdefine_include_file $drv_handle "xparameters.h" "XAp_ctl_handler" \
        "NUM_INSTANCES" \
        "DEVICE_ID" \
        "C_S_AXI_AXI4LITES_BASEADDR" \
        "C_S_AXI_AXI4LITES_HIGHADDR"

    xdefine_config_file $drv_handle "xap_ctl_handler_g.c" "XAp_ctl_handler" \
        "DEVICE_ID" \
        "C_S_AXI_AXI4LITES_BASEADDR"

    xdefine_canonical_xpars $drv_handle "xparameters.h" "XAp_ctl_handler" \
        "DEVICE_ID" \
        "C_S_AXI_AXI4LITES_BASEADDR" \
        "C_S_AXI_AXI4LITES_HIGHADDR"
}

