// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.4
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// AXI4LiteS
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : reserved
// 0x14 : Data signal of ap_start_enable
//        bit 0  - ap_start_enable[0] (Read/Write)
//        others - reserved
// 0x18 : reserved
// 0x1c : Data signal of ap_status_out_V
//        bit 2~0 - ap_status_out_V[2:0] (Read/Write)
//        others  - reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XAP_CTL_HANDLER_AXI4LITES_ADDR_AP_START_ENABLE_DATA 0x14
#define XAP_CTL_HANDLER_AXI4LITES_BITS_AP_START_ENABLE_DATA 1
#define XAP_CTL_HANDLER_AXI4LITES_ADDR_AP_STATUS_OUT_V_DATA 0x1c
#define XAP_CTL_HANDLER_AXI4LITES_BITS_AP_STATUS_OUT_V_DATA 3

