// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.4
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xap_ctl_handler.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XAp_ctl_handler_CfgInitialize(XAp_ctl_handler *InstancePtr, XAp_ctl_handler_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axi4lites_BaseAddress = ConfigPtr->Axi4lites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XAp_ctl_handler_SetAp_start_enable(XAp_ctl_handler *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAp_ctl_handler_WriteReg(InstancePtr->Axi4lites_BaseAddress, XAP_CTL_HANDLER_AXI4LITES_ADDR_AP_START_ENABLE_DATA, Data);
}

u32 XAp_ctl_handler_GetAp_start_enable(XAp_ctl_handler *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAp_ctl_handler_ReadReg(InstancePtr->Axi4lites_BaseAddress, XAP_CTL_HANDLER_AXI4LITES_ADDR_AP_START_ENABLE_DATA);
    return Data;
}

void XAp_ctl_handler_SetAp_status_out_v(XAp_ctl_handler *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAp_ctl_handler_WriteReg(InstancePtr->Axi4lites_BaseAddress, XAP_CTL_HANDLER_AXI4LITES_ADDR_AP_STATUS_OUT_V_DATA, Data);
}

u32 XAp_ctl_handler_GetAp_status_out_v(XAp_ctl_handler *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAp_ctl_handler_ReadReg(InstancePtr->Axi4lites_BaseAddress, XAP_CTL_HANDLER_AXI4LITES_ADDR_AP_STATUS_OUT_V_DATA);
    return Data;
}

