set sim_status(wrapc_needed)  1
set sim_status(bc_needed)     0
set sim_status(sc_needed)     1
set sim_status(pc_needed)     1
set sim_status(vhdl_needed)   0
set sim_status(vlog_needed)   0
set sim_status(bc_tb_needed)  0
set sim_status(cas_needed)    0
set sim_DirAutoSimRoot        "sim"
set sim_DirAutoSimTv          "sim/tv"
set sim_DirAutoSimBc          "sim/bc"
set sim_DirAutoSimSc          "sim/systemc"
set sim_DirAutoSimPostCheck   "sim/wrapc_pc"
set sim_DirAutoSimCasSc       "sim/casc"
set sim_DirAutoSimVhdl        "sim/vhdl"
set sim_DirAutoSimVlog        "sim/verilog"
set sim_DirAutoSimVlogGate    "sim/verilog.gate"
set sim_DirAutoSimWrapc       "sim/wrapc"
set sim_WorkingDir            "../.."
set sim_ConstFileTvIn         "ap_ctl_handler.autotvin.dat"
set sim_ConstFileTvOut        "ap_ctl_handler.autotvout.dat"
set sim_ConstFileHdlTvIn      "ap_ctl_handler.hdltvin.dat"
set sim_ConstFileHdlTvOut     "ap_ctl_handler.hdltvout.dat"
set sim_GateLevelSim          0
set sim_GTool                 "auto"
set sim_GAutowrap             1
set sim_GTvIn                 "../../sim/tv/ap_ctl_handler.autotvin.dat"
set sim_GTvOut                "../../sim/tv/ap_ctl_handler.autotvout.dat"
set sim_GHdlTvIn              "../../sim/tv/ap_ctl_handler.hdltvin.dat"
set sim_GHdlTvOut             "../../sim/tv/ap_ctl_handler.hdltvout.dat"
