// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _ap_ctl_handler_HH_
#define _ap_ctl_handler_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct ap_ctl_handler : public sc_module {
    // Port declarations 10
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_logic > ap_start_enable;
    sc_out< sc_logic > ap_start_out;
    sc_in< sc_logic > ap_ready_in;
    sc_in< sc_logic > ap_done_in;
    sc_in< sc_logic > ap_idle_in;
    sc_in< sc_lv<3> > ap_status_out_V;
    // Port declarations for the virtual clock. 
    sc_in_clk ap_virtual_clock;


    // Module declarations
    ap_ctl_handler(sc_module_name name);
    SC_HAS_PROCESS(ap_ctl_handler);

    ~ap_ctl_handler();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<1> > p_s_fu_78_p0;
    sc_signal< sc_lv<1> > current_status_V_fu_86_p0;
    sc_signal< sc_lv<1> > current_status_V_1_fu_94_p0;
    sc_signal< sc_lv<3> > current_status_V_fu_86_p3;
    sc_signal< sc_lv<3> > p_s_fu_78_p3;
    sc_signal< sc_lv<3> > current_status_V_1_fu_94_p3;
    sc_signal< sc_lv<2> > tmp_1_fu_102_p4;
    sc_signal< sc_lv<1> > p_04_1_fu_120_p0;
    sc_signal< sc_lv<3> > current_status_V_2_fu_112_p3;
    sc_signal< sc_lv<3> > p_04_1_fu_120_p3;
    static const sc_logic ap_const_logic_1;
    static const bool ap_true;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_const_lv3_4;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<3> ap_const_lv3_6;
    static const sc_lv<3> ap_const_lv3_2;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_1;
    // Thread declarations
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_start_out();
    void thread_current_status_V_1_fu_94_p0();
    void thread_current_status_V_1_fu_94_p3();
    void thread_current_status_V_2_fu_112_p3();
    void thread_current_status_V_fu_86_p0();
    void thread_current_status_V_fu_86_p3();
    void thread_p_04_1_fu_120_p0();
    void thread_p_04_1_fu_120_p3();
    void thread_p_s_fu_78_p0();
    void thread_p_s_fu_78_p3();
    void thread_tmp_1_fu_102_p4();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
