// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================


extern void ap_ctl_handler ( bool ap_start_enable,  bool* ap_start_out,  bool ap_ready_in,  bool ap_done_in,  bool ap_idle_in,  ap_uint<3>* ap_status_out);

