// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.4
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XAP_CTL_HANDLER_H
#define XAP_CTL_HANDLER_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xap_ctl_handler_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axi4lites_BaseAddress;
} XAp_ctl_handler_Config;
#endif

typedef struct {
    u32 Axi4lites_BaseAddress;
    u32 IsReady;
} XAp_ctl_handler;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XAp_ctl_handler_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XAp_ctl_handler_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XAp_ctl_handler_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XAp_ctl_handler_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XAp_ctl_handler_Initialize(XAp_ctl_handler *InstancePtr, u16 DeviceId);
XAp_ctl_handler_Config* XAp_ctl_handler_LookupConfig(u16 DeviceId);
int XAp_ctl_handler_CfgInitialize(XAp_ctl_handler *InstancePtr, XAp_ctl_handler_Config *ConfigPtr);
#else
int XAp_ctl_handler_Initialize(XAp_ctl_handler *InstancePtr, const char* InstanceName);
int XAp_ctl_handler_Release(XAp_ctl_handler *InstancePtr);
#endif


void XAp_ctl_handler_SetAp_start_enable(XAp_ctl_handler *InstancePtr, u32 Data);
u32 XAp_ctl_handler_GetAp_start_enable(XAp_ctl_handler *InstancePtr);
void XAp_ctl_handler_SetAp_status_out_v(XAp_ctl_handler *InstancePtr, u32 Data);
u32 XAp_ctl_handler_GetAp_status_out_v(XAp_ctl_handler *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
